name: weather_app
description: A weather application using clean architecture.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  dio: ^5.4.0
  geolocator: ^10.1.0
  connectivity_plus: ^6.1.3
  device_preview: ^1.2.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  flutter_offline: ^4.0.0
  flutter_svg: ^2.0.9
  intl: 0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#F3E8F4" # Color of the background of the splash screen
  image: assets/master/splash_screen.png # image path
  android_12:
    image: assets/master/splash_screen.png # image path
    color: "#F3E8F4" # Color of the background of the splash screen

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/master/icon.png" # Logo image path
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/master/
    - assets/icons/
